name: robot framework cicd

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute test 01
        run: |
          robot -i func -d report/ -o "output_01.xml" testcases/func01/*.robot
           
      - name: execute test 02
        run: | 
          robot -i func -d report/ -o "output_02.xml" testcases/func02/*.robot


     - name: merge logs
        run: |
          rebot -N "Output" -o "output_pub.xml" -l "log.html" -r "report.html" -d report output_01.xml public output_02.xml
