name: Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Build
    #   run: |
    #     # Add your build commands here

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        test_suites="robot -i func testcases/*/*.robot"
        output_logs="report"
        for suite in $test_suites
        do
          output_log=$(basename "$suite" .robot).xml
          robot --output $output_log $suite
          output_logs="$output_logs $output_log"
        done
        rebot --outputdir log_report --merge $output_logs

    # - name: Send report to Slack
    #   if: always()
    #   uses: rtCamp/action-slack-notify@v3
    #   with:
    #     status: ${{ job.status }}
    #     text: "Test report: ${{ github.event.repository.name }} ${{ github.sha }}\nView report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}