name: Build and Test

on:
  push: 
    branches:
      - regression


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test_func01:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        robot -i func -d python_function -o "output_01.xml" testcases/func1/calculate1.robot
        
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: reports
        path: python_function

    


    # - name: merge logs
    #   run: |
    #     rebot -d report/ -o "output_pub.xml" -l "log_pub.html" -r "report_pub.html" --merge report/output_01.xml report/output_02.xml

  test_func02:
    runs-on: windows-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        robot -i two -d python_function -o "output_02.xml" testcases/func2/calculate2.robot
        
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: reports
        path: python_function
        
        
  generate_report:
        if: always()
        needs: [test_func01, test_func02] 
        runs-on: windows-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports

        - name: Get Repository Owner & Name
          run: |
            set-env OWNER="$(echo "${{github.repository_owner}}" | awk -F / '{print $3}')"
            set-env REPO="$(echo "${{github.repository}}" | awk -F / '{print $3}')"
            echo "::set-env name=REPOSITORY_OWNER::$OWNER"
            echo "::set-env name=REPOSITORY_NAME::$REPO"

        # - name: Send report to commit
        #   uses: actions/upload-artifact@v1
        #   env:
        #     GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
        #     REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
        #     COMMIT_SHA: ${{ github.sha }}
        #     REPOSITORY: ${{ env.REPOSITORY_NAME }}
        #     REPORT_PATH: report

        - name: Commit Log Report
          uses: enriquesanchez/commit-log-report@v1.0.0
          with:
            branch: regression
          env:
            GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
            REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: report

    
  # merge_log:
  #   runs-on: windows-latest
  #   needs: [build, test_func01, test_func02]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: merge logs
  #     run: |
  #       rebot -d report -o "output_pub.xml" -l "log_pub.html" -r "report_pub.html" --merge report/output_01.xml
    
  # read_report:
  #   runs-on: windows-latest
  #   needs: [build, test_func01, test_func02]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: setup python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10' # install the python version needed
    
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pandas
  #       pip install python-dotenv
  #       pip install elementpath
  #       pip install DateTime
  #       pip install python-time

  #   - name: read report
  #     run: |
  #       python python_function/python.py

    # - name: Send report to Slack
    #   if: always()
    #   uses: rtCamp/action-slack-notify@v3
    #   with:
    #     status: ${{ job.status }}
    #     text: "Test report: ${{ github.event.repository.name }} ${{ github.sha }}\nView report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
